import os
import numpy as np
import cv2
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def save_overlay(image: Image.Image, heatmap, bbox, save_path):
    """
    сохраняем картинку с heatmap + bbox
    """

    image = np.array(image).copy()
    image = cv2.resize(image, (224, 224))

    heatmap = heatmap.cpu().numpy()
    heatmap = cv2.resize(heatmap, (224, 224))
    heatmap = (heatmap * 255).astype(np.uint8)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    overlay = cv2.addWeighted(image, 0.6, heatmap, 0.4, 0)

    if bbox is not None:
        x1, y1, x2, y2 = bbox["x1"], bbox["y1"], bbox["x2"], bbox["y2"]
        cv2.rectangle(overlay, (x1, y1), (x2, y2), (0, 255, 0), 2)

    cv2.imwrite(save_path, overlay)


def generate_pdf_report(
    image_path,
    heatmap,
    bbox,
    score,
    label,
    output_path="report.pdf"
):

    os.makedirs("runs/reports", exist_ok=True)

    overlay_path = "runs/reports/overlay.png"

    image = Image.open(image_path).convert("RGB")

    # 1) save overlay image
    save_overlay(image, heatmap, bbox, overlay_path)

    # 2) create PDF
    c = canvas.Canvas(output_path, pagesize=A4)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 800, "Industrial Defect Detection Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, 770, f"Score: {score:.4f}")
    c.drawString(50, 750, f"Label: {'DEFECT' if label == 1 else 'NORMAL'}")

    # image
    c.drawImage(overlay_path, 50, 400, width=500, height=300)

    c.drawString(50, 370, "Generated by PatchCore + CNN system")

    c.save()

    return output_path